# see https://crates.io/crates/cargo-make

[env]
RUST_TEST_THREADS = "1"
CARGO_MAKE_TEST_COVERAGE_BINARY_FILTER = "cli-[a-z0-9]*$\\|makers-[a-z0-9]*$\\|${CARGO_MAKE_TEST_COVERAGE_DEFAULT_BINARY_FILTER}"
SHOWATA_MEDIUM="Noop"

[tasks.publish]
command = "cargo"
args = ["release", "${@}"]

[tasks.run-all-examples.env]
SHOWATA_MEDIUM = "BROWSER"
[tasks.run-all-examples]
script = [
    "for example in examples/*.rs; do echo $example; cargo run --example $(basename $example | cut -f 1 -d '.'); done"
]
